version: "3.6"
services:
   db:
      container_name: db_host
      image: mariadb:latest
      volumes:
         - crud_php_fsd:/var/lib/mysql
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=crud_php
         - MYSQL_USER=crud_php
         - MYSQL_PASSWORD=crud_php
      restart: always
      networks:
         - crud_php_network

   web:
      build: ./
      working_dir: /var/www/html
      volumes:
         - ./:/var/www/html
      ports:
         - "8000:80"
      links:
         - db
      depends_on:
         - db
      restart: always
      networks:
         - crud_php_network

   phpmyadmin:
      image: phpmyadmin
      ports:
         - 8080:80
      environment:
         - PMA_HOST=db
      depends_on:
         - db
      networks:
         - crud_php_network

volumes:
   crud_php_fsd:
networks:
   crud_php_network:
